from dataclasses import dataclass
import pyxel

ROW = 20
COL = 20
DIM = 16

TANK_LENGTH = 16
TANK_WIDTH = 16
CONTROLS = {
           pyxel.KEY_W: "north",
           pyxel.KEY_A: "west",
           pyxel.KEY_S: "south",
           pyxel.KEY_D: "east",
           }

@dataclass
class Tank:
   x: float
   y: float
   vx: float
   vy: float
   dir: str
   type: str
   is_alive: bool

@dataclass
class Bullet:
   x: float
   y: float
   vx: int
   vy: int
   shooter: str

@dataclass
class Cell:
   i: int
   j: int
   w: int
   h: int
   type: str | None
   is_blank: bool

@dataclass
class Level:
   name: str
   player_tank: list[Tank]
   enemy_tanks: list[Tank]
   enemy_tanks_num: int
   is_game_over: bool
   cells: list[Cell]
   is_winner: bool

class Levels:
   def __init__(self) -> None:
       self.level_1 = Level("level_1", player_tank = [Tank(135, 230, 0, 0, "north", "player", True)],
                                       enemy_tanks = [Tank(20, 20, 0, 0, "east", "enemy", True),
                                                     Tank(250, 20, 0, 0, "west", "enemy", True),
                                                     Tank(20, 270, 0, 0, "west", "enemy", True),
                                                     Tank(250, 270, 0, 0, "west", "enemy", True),
                                                     Tank(150, 150, 0, 0, "west", "enemy", True),
                                                     ],
                           enemy_tanks_num = 5, is_game_over = False,
                           cells = [Cell(18, 8, DIM, DIM, 'home', False),
                               Cell(18, 7, DIM, DIM, 'brick', False),
                               Cell(17, 7, DIM, DIM, 'brick', False),
                               Cell(17, 8, DIM, DIM, 'brick', False),
                               Cell(17, 9, DIM, DIM, 'brick', False),
                               Cell(18, 9, DIM, DIM, 'brick', False),
                               Cell(14, 4, DIM, DIM, 'water', False),
                               Cell(14, 3, DIM, DIM, 'water', False),
                               Cell(13, 4, DIM, DIM, 'water', False),
                               Cell(13, 3, DIM, DIM, 'water', False),
                               Cell(13, 5, DIM, DIM, 'water', False),
                               Cell(13, 2, DIM, DIM, 'forest', False),
                               Cell(12, 4, DIM, DIM, 'water', False),
                               Cell(12, 5, DIM, DIM, 'water', False),
                               Cell(11, 4, DIM, DIM, 'forest', False),
                               Cell(11, 5, DIM, DIM, 'forest', False),
                               Cell(11, 3, DIM, DIM, 'forest', False),
                               Cell(12, 3, DIM, DIM, 'forest', False),
                               Cell(12, 2, DIM, DIM, 'forest', False),   
                               Cell(14, 2, DIM, DIM, 'forest', False),
                               Cell(15, 3, DIM, DIM, 'forest', False),
                               Cell(15, 4, DIM, DIM, 'forest', False),
                               Cell(15, 5, DIM, DIM, 'forest', False),
                               Cell(14, 5, DIM, DIM, 'forest', False),
                               Cell(14, 6, DIM, DIM, 'forest', False),
                               Cell(13, 6, DIM, DIM, 'forest', False),
                               Cell(12, 6, DIM, DIM, 'forest', False),
                               Cell(11, 6, DIM, DIM, 'forest', False),
                               Cell(13, 7, DIM, DIM, 'forest', False),
                               Cell(13, 8, DIM, DIM, 'forest', False),
                               Cell(13, 9, DIM, DIM, 'forest', False),
                               Cell(13, 10, DIM, DIM, 'forest', False),
                               Cell(13, 11, DIM, DIM, 'forest', False),
                               Cell(12, 7, DIM, DIM, 'forest', False),
                               Cell(12, 8, DIM, DIM, 'forest', False),
                               Cell(12, 9, DIM, DIM, 'forest', False),
                               Cell(12, 10, DIM, DIM, 'forest', False),
                               Cell(12, 11, DIM, DIM, 'forest', False),
                               Cell(11, 11, DIM, DIM, 'forest', False),
                               Cell(11, 12, DIM, DIM, 'water', False),
                               Cell(12, 12, DIM, DIM, 'water', False),
                               Cell(11, 13, DIM, DIM, 'water', False),
                               Cell(12, 13, DIM, DIM, 'water', False),
                               Cell(11, 14, DIM, DIM, 'water', False),
                               Cell(12, 14, DIM, DIM, 'forest', False),
                               Cell(12, 15, DIM, DIM, 'forest', False),
                               Cell(13, 14, DIM, DIM, 'forest', False),
                               Cell(13, 13, DIM, DIM, 'forest', False),
                               Cell(13, 12, DIM, DIM, 'forest', False),
                               Cell(11, 15, DIM, DIM, 'forest', False),
                               Cell(10, 14, DIM, DIM, 'forest', False),
                               Cell(10, 13, DIM, DIM, 'forest', False),
                               Cell(10, 12, DIM, DIM, 'forest', False),
                               Cell(14, 12, DIM, DIM, 'brick', False),
                               Cell(18, 11, DIM, DIM, 'stone', False),
                               Cell(14, 13, DIM, DIM, 'brick', False),
                               Cell(14, 14, DIM, DIM, 'cracked_brick', False),
                               Cell(15, 14, DIM, DIM, 'brick', False),
                               Cell(16, 14, DIM, DIM, 'stone', False),
                               Cell(17, 14, DIM, DIM, 'cracked_brick', False),      
                               Cell(16, 4, DIM, DIM, 'brick', False),
                               Cell(16, 3, DIM, DIM, 'cracked_brick', False),
                               Cell(17, 3, DIM, DIM, 'cracked_brick', False),
                               Cell(18, 3, DIM, DIM, 'brick', False),
                               Cell(16, 3, DIM, DIM, 'cracked_brick', False),
                               Cell(8, 6, DIM, DIM, 'southeast_mirror', False),
                               Cell(8, 11, DIM, DIM, 'northeast_mirror', False),
                               Cell(6, 4, DIM, DIM, 'cracked_brick', False),
                               Cell(6, 5, DIM, DIM, 'brick', False),
                               Cell(6, 6, DIM, DIM, 'brick', False),
                               Cell(6, 7, DIM, DIM, 'brick', False),
                               Cell(6, 8, DIM, DIM, 'cracked_brick', False),
                               Cell(6, 9, DIM, DIM, 'cracked_brick', False),
                               Cell(6, 10, DIM, DIM, 'brick', False),
                               Cell(6, 11, DIM, DIM, 'cracked_brick', False),
                               Cell(6, 12, DIM, DIM, 'brick', False),
                               Cell(6, 13, DIM, DIM, 'brick', False),
                               Cell(5, 4, DIM, DIM, 'brick', False),
                               Cell(4, 4, DIM, DIM, 'brick', False),
                               Cell(3, 4, DIM, DIM, 'brick', False),
                               Cell(3, 5, DIM, DIM, 'cracked_brick', False),
                               Cell(5, 13, DIM, DIM, 'brick', False),
                               Cell(4, 13, DIM, DIM, 'brick', False),
                               Cell(3, 13, DIM, DIM, 'brick', False),
                               Cell(3, 6, DIM, DIM, 'brick', False),
                               Cell(3, 7, DIM, DIM, 'brick', False),
                               Cell(3, 8, DIM, DIM, 'cracked_brick', False),
                               Cell(3, 9, DIM, DIM, 'cracked_brick', False),
                               Cell(3, 10, DIM, DIM, 'brick', False),
                               Cell(3, 11, DIM, DIM, 'cracked_brick', False),
                               Cell(3, 12, DIM, DIM, 'brick', False),
                               Cell(15, 2, DIM, DIM, 'brick', False),
                               Cell(15, 1, DIM, DIM, 'brick', False),
                               Cell(14, 15, DIM, DIM, 'brick', False),
                               Cell(14, 16, DIM, DIM, 'brick', False),
                               Cell(14, 16, DIM, DIM, 'brick', False),
                               Cell(10, 4, DIM, DIM, 'brick', False),
                               Cell(9, 4, DIM, DIM, 'brick', False),
                               Cell(8, 4, DIM, DIM, 'brick', False),
                               Cell(7, 4, DIM, DIM, 'stone', False),
                               Cell(9, 13, DIM, DIM, 'stone', False),
                               Cell(8, 13, DIM, DIM, 'brick', False),
                               Cell(7, 13, DIM, DIM, 'brick', False),
                               Cell(4, 12, DIM, DIM, 'southeast_mirror', False),
                               Cell(4, 5, DIM, DIM, 'northeast_mirror', False),
                               Cell(4, 1, DIM, DIM, 'forest', False),
                               Cell(5, 1, DIM, DIM, 'forest', False),
                               Cell(4, 2, DIM, DIM, 'forest', False),
                               Cell(5, 2, DIM, DIM, 'forest', False),
                               Cell(4, 3, DIM, DIM, 'forest', False),
                               Cell(5, 3, DIM, DIM, 'forest', False),
                               Cell(4, 14, DIM, DIM, 'forest', False),
                               Cell(5, 14, DIM, DIM, 'forest', False),
                               Cell(4, 15, DIM, DIM, 'forest', False),
                               Cell(5, 15, DIM, DIM, 'forest', False),
                               Cell(4, 16, DIM, DIM, 'forest', False),
                               Cell(5, 16, DIM, DIM, 'forest', False),
                               Cell(2, 4, DIM, DIM, 'forest', False),
                               Cell(2, 13, DIM, DIM, 'forest', False),
                               Cell(1, 4, DIM, DIM, 'forest', False),
                               Cell(1, 13, DIM, DIM, 'forest', False),
                               Cell(9, 1, DIM, DIM, 'brick', False),
                               Cell(9, 2, DIM, DIM, 'brick', False),
                               Cell(9, 3, DIM, DIM, 'brick', False),
                               Cell(8, 14, DIM, DIM, 'brick', False),
                               Cell(8, 15, DIM, DIM, 'brick', False),
                               Cell(8, 16, DIM, DIM, 'brick', False),
                      ]+[Cell(i, 0, DIM, DIM, "stone", True) for i in range(ROW)]+\
                      [Cell(0, j, DIM, DIM, "stone", True) for j in range(ROW)] + \
                      [Cell(COL-1, j, DIM, DIM, "stone", True) for j in range(ROW)] + \
                      [Cell(i, ROW-1, DIM, DIM, "stone", True) for i in range(ROW)] + \
                      [Cell(i, ROW-2, DIM, DIM, "stone", True) for i in range(ROW)] +\
                      [Cell(i, ROW-3, DIM, DIM, "stone", True) for i in range(ROW)],
                       is_winner=False)
      
       self.level_2 = Level("level_2", player_tank = [Tank(135, 230, 0, 0, "north", "player", True)],
                                      enemy_tanks = [Tank(80, 80, 0, 0, "east", "enemy", True),
                                                     Tank(190, 80, 0, 0, "west", "enemy", True),
                                                     Tank(20, 200, 0, 0, "east", "enemy", True),
                                                     Tank(250, 200, 0, 0, "west", "enemy", True),
                                                     Tank(120, 150, 0, 0, "east", "enemy", True),
                                                     Tank(140, 150, 0, 0, "west", "enemy", True),
                                                     Tank(20, 280, 0, 0, "east", "enemy", True),
                                                     Tank(250, 280, 0, 0, "west", "enemy", True),
                                                     Tank(80, 80, 0, 0, "east", "enemy", True),
                                                     Tank(190, 80, 0, 0, "west", "enemy", True),
                                                     ],
                           enemy_tanks_num = 10, is_game_over = False,
                           cells = [Cell(18, 8, DIM, DIM, 'home', False),
                                  Cell(18, 9, DIM, DIM, 'stone', False),
                                  Cell(18, 7, DIM, DIM, 'brick', False),
                                  Cell(16, 8, DIM, DIM, 'brick', False),
                                  Cell(16, 9, DIM, DIM, 'forest', False),
                                  Cell(18, 6, DIM, DIM, 'brick', False),
                                  Cell(18, 3, DIM, DIM, 'brick', False),
                                  Cell(17, 3, DIM, DIM, 'stone', False),
                                  Cell(16, 3, DIM, DIM, 'stone', False),
                                  Cell(15, 3, DIM, DIM, 'forest', False),
                                  Cell(15, 4, DIM, DIM, 'forest', False),
                                  Cell(18, 14, DIM, DIM, 'brick', False),
                                  Cell(17, 14, DIM, DIM, 'stone', False),
                                  Cell(16, 14, DIM, DIM, 'stone', False),
                                  Cell(15, 14, DIM, DIM, 'forest', False),
                                  Cell(15, 13, DIM, DIM, 'forest', False),
                                  Cell(18, 10, DIM, DIM, 'brick', False),
                                  Cell(18, 11, DIM, DIM, 'brick', False),
                                  Cell(17, 7, DIM, DIM, 'cracked_brick', False),
                                  Cell(17, 8, DIM, DIM, 'brick', False),
                                  Cell(17, 9, DIM, DIM, 'forest', False),
                                  Cell(17, 10, DIM, DIM, 'cracked_brick', False),
                                  Cell(12, 8, DIM, DIM, 'brick', False),
                                  Cell(12, 9, DIM, DIM, 'brick', False),
                                  Cell(12, 7, DIM, DIM, 'brick', False),
                                  Cell(11, 10, DIM, DIM, 'brick', False),
                                  Cell(11, 8, DIM, DIM, 'brick', False),
                                  Cell(11, 9, DIM, DIM, 'brick', False),
                                  Cell(11, 7, DIM, DIM, 'brick', False),
                                  Cell(11, 10, DIM, DIM, 'brick', False),
                                  Cell(12, 10, DIM, DIM, 'brick', False),
                                  Cell(12, 6, DIM, DIM, 'water', False),
                                  Cell(12, 11, DIM, DIM, 'water', False),
                                  Cell(11, 6, DIM, DIM, 'water', False),
                                  Cell(11, 11, DIM, DIM, 'water', False),
                                  Cell(11, 5, DIM, DIM, 'water', False),
                                  Cell(11, 12, DIM, DIM, 'water', False),
                                  Cell(10, 6, DIM, DIM, 'water', False),
                                  Cell(10, 11, DIM, DIM, 'water', False),
                                  Cell(10, 5, DIM, DIM, 'water', False),
                                  Cell(10, 12, DIM, DIM, 'water', False),
                                  Cell(9, 5, DIM, DIM, 'water', False),
                                  Cell(9, 12, DIM, DIM, 'water', False),
                                  Cell(8, 5, DIM, DIM, 'water', False),
                                  Cell(8, 12, DIM, DIM, 'water', False),
                                  Cell(7, 5, DIM, DIM, 'water', False),
                                  Cell(7, 12, DIM, DIM, 'water', False),
                                  Cell(8, 6, DIM, DIM, 'water', False),
                                  Cell(8, 11, DIM, DIM, 'water', False),
                                  Cell(7, 6, DIM, DIM, 'water', False),
                                  Cell(7, 11, DIM, DIM, 'water', False),
                                  Cell(8, 7, DIM, DIM, 'brick', False),
                                  Cell(8, 10, DIM, DIM, 'brick', False),
                                  Cell(7, 7, DIM, DIM, 'brick', False),
                                  Cell(7, 10, DIM, DIM, 'cracked_brick', False),
                                  Cell(8, 8, DIM, DIM, 'cracked_brick', False),
                                  Cell(8, 9, DIM, DIM, 'cracked_brick', False),
                                  Cell(7, 8, DIM, DIM, 'brick', False),
                                  Cell(7, 9, DIM, DIM, 'brick', False),
                                  Cell(6, 8, DIM, DIM, 'brick', False),
                                  Cell(6, 9, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 7, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 10, DIM, DIM, 'cracked_brick', False),
                                  Cell(5, 8, DIM, DIM, 'cracked_brick', False),
                                  Cell(5, 9, DIM, DIM, 'brick', False),
                                  Cell(4, 8, DIM, DIM, 'brick', False),
                                  Cell(4, 9, DIM, DIM, 'brick', False),
                                  Cell(3, 8, DIM, DIM, 'brick', False),
                                  Cell(3, 9, DIM, DIM, 'brick', False),
                                  Cell(3, 7, DIM, DIM, 'brick', False),
                                  Cell(3, 6, DIM, DIM, 'cracked_brick', False),
                                  Cell(3, 5, DIM, DIM, 'cracked_brick', False),
                                  Cell(3, 10, DIM, DIM, 'brick', False),
                                  Cell(3, 11, DIM, DIM, 'brick', False),
                                  Cell(3, 12, DIM, DIM, 'brick', False),
                                  Cell(3, 13, DIM, DIM, 'brick', False),
                                  Cell(4, 13, DIM, DIM, 'brick', False),
                                  Cell(4, 14, DIM, DIM, 'cracked_brick', False),
                                  Cell(5, 14, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 14, DIM, DIM, 'brick', False),
                                  Cell(7, 14, DIM, DIM, 'brick', False),
                                  Cell(8, 14, DIM, DIM, 'brick', False),
                                  Cell(9, 14, DIM, DIM, 'brick', False),
                                  Cell(10, 14, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 13, DIM, DIM, 'cracked_brick', False),
                                  Cell(7, 13, DIM, DIM, 'cracked_brick', False),
                                  Cell(8, 13, DIM, DIM, 'v', False),
                                  Cell(9, 13, DIM, DIM, 'brick', False),
                                  Cell(10, 13, DIM, DIM, 'cracked_brick', False),
                                  Cell(11, 13, DIM, DIM, 'cracked_brick', False),
                                  Cell(5, 15, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 15, DIM, DIM, 'brick', False),
                                  Cell(7, 15, DIM, DIM, 'brick', False),
                                  Cell(8, 15, DIM, DIM, 'brick', False),
                                  Cell(9, 15, DIM, DIM, 'brick', False),
                                  Cell(4, 3, DIM, DIM, 'brick', False),
                                  Cell(4, 4, DIM, DIM, 'cracked_brick', False),
                                  Cell(3, 4, DIM, DIM, 'cracked_brick', False),
                                  Cell(5, 3, DIM, DIM, 'cracked_brick', False),
                                  Cell(6, 3, DIM, DIM, 'brick', False),
                                  Cell(7, 3, DIM, DIM, 'brick', False),
                                  Cell(8, 3, DIM, DIM, 'brick', False),
                                  Cell(9, 3, DIM, DIM, 'brick', False),
                                  Cell(10, 3, DIM, DIM, 'brick', False),
                                  Cell(6, 4, DIM, DIM, 'brick', False),
                                  Cell(7, 4, DIM, DIM, 'brick', False),
                                  Cell(8, 4, DIM, DIM, 'brick', False),
                                  Cell(9, 4, DIM, DIM, 'brick', False),
                                  Cell(10, 4, DIM, DIM, 'brick', False),
                                  Cell(11, 4, DIM, DIM, 'brick', False),
                                  Cell(5, 2, DIM, DIM, 'brick', False),
                                  Cell(6, 2, DIM, DIM, 'brick', False),
                                  Cell(7, 2, DIM, DIM, 'brick', False),
                                  Cell(8, 2, DIM, DIM, 'cracked_brick', False),
                                  Cell(9, 2, DIM, DIM, 'cracked_brick', False),
                                  Cell(2, 5, DIM, DIM, 'cracked_brick', False),
                                  Cell(2, 6, DIM, DIM, 'cracked_brick', False),
                                  Cell(2, 7, DIM, DIM, 'brick', False),
                                  Cell(2, 8, DIM, DIM, 'cracked_brick', False),
                                  Cell(2, 9, DIM, DIM, 'brick', False),
                                  Cell(2, 10, DIM, DIM, 'brick', False),
                                  Cell(2, 11, DIM, DIM, 'brick', False),
                                  Cell(2, 12, DIM, DIM, 'brick', False),
                                  Cell(5, 6, DIM, DIM, 'northeast_mirror', False),
                                  Cell(5, 11, DIM, DIM, 'southeast_mirror', False),
                                  Cell(14, 4, DIM, DIM, 'forest', False),
                                  Cell(13, 4, DIM, DIM, 'forest', False),
                                  Cell(12, 4, DIM, DIM, 'forest', False),
                                  Cell(8, 13, DIM, DIM, 'cracked_brick', False),
                                  Cell(14, 13, DIM, DIM, 'forest', False),
                                  Cell(13, 13, DIM, DIM, 'forest', False),
                                  Cell(12, 13, DIM, DIM, 'forest', False),
                                  Cell(11, 14, DIM, DIM, 'forest', False),
                                  Cell(11, 15, DIM, DIM, 'forest', False),
                                  Cell(11, 16, DIM, DIM, 'forest', False),
                                  Cell(11, 1, DIM, DIM, 'forest', False),
                                  Cell(11, 2, DIM, DIM, 'forest', False),
                                  Cell(11, 3, DIM, DIM, 'forest', False),
                                  Cell(15, 1, DIM, DIM, 'forest', False),
                                  Cell(15, 2, DIM, DIM, 'forest', False),
                                  Cell(15, 15, DIM, DIM, 'forest', False),
                                  Cell(15, 16, DIM, DIM, 'forest', False)
                      ]+[Cell(i, 0, DIM, DIM, "stone",True) for i in range(ROW)]+\
                      [Cell(0, j, DIM, DIM, "stone",True) for j in range(ROW)] + \
                      [Cell(COL-1, j, DIM, DIM, "stone",True) for j in range(ROW)] + \
                      [Cell(i, ROW-1, DIM, DIM, "stone",True) for i in range(ROW)] + \
                      [Cell(i, ROW-2, DIM, DIM, "stone",True) for i in range(ROW)] +\
                      [Cell(i, ROW-3, DIM, DIM, "stone",True) for i in range(ROW)],
                      is_winner=False)
      
       self.list_of_levels: list[Level] = [self.level_1, self.level_2]
